<link rel="stylesheet" href="<?= $wwwUrl ?>/css/around.css">

<section class="header-landing header-around">
  <article class="titles-header-landing">
    <h1 class="title title-header-landing">La Charentes et ses alentours</h1>
    <h2 class="title subtitle-header-landing">Découvrir la région</h2>
  </article>
</section>
<section class="container-landing container-landing-first">
  <div class="around-container">
    <img class="around-picture" src="<?= $wwwUrl ?>/images/around/1.jpg" alt="La ville de Cognac">
    <article class="around-wrapper">
      <h2 class="title around-title">La ville de Cognac</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </article>
  </div>
  <a class="cta-around" href="<?= $requestUrl ?>/around/places">Nos adresses coup de coeur</a>
</section>
<section class="container-landing container-landing-second">
  <div class="around-container">
    <article class="around-wrapper">
      <h2 class="title around-title">La Rochelle</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </article>
    <img class="around-picture" src="<?= $wwwUrl ?>/images/around/2.jpg" alt="La Rochelle">
  </div>
  <a class="cta-around" href="<?= $requestUrl ?>/around/places">Nos adresses coup de coeur</a>
</section>
<section class="container-landing container-landing-second more">
  <h3 class="title around-subtitle">Pour en découvrir plus sur Cognac et sa région</h3>
  <aside class="more-about">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <ul class="more-about-list">
      <li><a href="https://www.lci.fr/regions/cognac-une-petite-ville-connue-dans-le-monde-entier-2122214.html" target="_blank">Cognac, une petite ville connue dans le monde entier</a></li>
      <li><a href="https://www.ville-cognac.fr/" target="_blank">Le site de la ville de Cognac</a></li>
      <li><a href="https://www.cognac.fr/" target="_blank">Le Cognac et son appelation</a></li>
    </ul>
  </aside>
</section>
<section class="container-landing container-landing-second">
  <aside class="partenaires">
    <h3 class="title around-subtitle">Découvrez nos partenaires</h3>
    <ul class="partenaires-list">
      <li class="partenaires-items"><a href="https://www.tourism-cognac.com/" target="_blank"><img src="<?= $wwwUrl ?>/images/around/logo-destination-cognac.png" alt="logo destination cognac" title="logo destination cognac"</a></li>
      <li class="partenaires-items"><a href="https://www.infiniment-charentes.com/" target="_blank"><img src="<?= $wwwUrl ?>/images/around/logo-infiniment-charentes.jpg" alt="logo destination cognac" title="logo destination cognac"</a></li>
    </ul>
  </aside>
</section>
