<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/rooms.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<section class="section-main-design room-presentation">
  <h2 class="title title-room-presentation"><?= $room["RoomName"] ?> (<?= $room["NumberOfPersonn"] ?>)</h3>
  <article class="room-introduction">
    <p><?= $room["Description"] ?></p>
    <?php if ($room["PlusBed"]) { ?>
      <p>Possibilité de mettre un lit supplémentaire (supplément 15 euros)</p>
    <?php } ?>
    <img class="room-picture" src="<?= $wwwUrl ?>/images/rooms<?= $room["PhotoMiniature"] ?>" alt="Photos de la chambre d'hôtes <?= $room["RoomName"] ?>">
    <article class="room-services">
      <ul class="room-presentation-list">
        <li>Entrée privative</li>
        <li>Chambre avec un lit <?= $room["Bed"] ?></li>
        <?php if ($room["SeperateWC"]) { ?>
          <li>Salle de douche et WC privatifs mais WC séparés</li>
        <?php } else { ?>
          <li>Salle de douche et WC privatifs</li>
        <?php } ?>
        <?php if ($room["RelaxSpace"]) { ?>
          <li>Coin Détente</li>
        <?php } ?>
        <?php if ($room["WithBabyBed"]) { ?>
          <li>Lit gigogne</li>
        <?php } ?>
        <?php if ($room["WithCouch"]) { ?>
          <li>Canapé</li>
        <?php } ?>
        <?php if ($room["Office"]) { ?>
          <li>Coin Bureau</li>
        <?php } ?>
      </ul>
    </article>
  </article>
  <aside class="room-prices">
    <h3>A partir de <?= $room["LowSeasonPriceDay"] ?>€</h3>
    <?php if ($room["PlusPersonn"]) { ?>
      <p>Supplément 10 € pour 1 personne supplémentaire</p>
    <?php } ?>
    <p>Petit déjeuner INCLUS</p>
    <div class="cta-rooms">
      <a class="cta" href="<?= $requestUrl ?>/rooms/room?RoomId=<?= $_GET["RoomId"] ?>"><i class="fas fa-plus-circle"></i> Voir plus</a>
    </div>
  </aside>
</section>
<section class="section-main-design">
  <form class="" action="<?= $requestUrl ?>/reservation" method="post">
    <h2>Réservez une chambre</h2>
    <label for="arrivalDate">Date d'arrivée</label>
    <input type="text" id="datePickerArrival" name="datePickerArrival">
    <label for="departureDate">Date de départ</label>
    <input type="text" id="datePickerDeparture" name="datePickerDeparture">
    <input type="hidden" name="roomId" value="<?= $_GET["RoomId"] ?>">
    <input type="submit" id="bookingCta" value="Réservez" />
  </form>
</section>


</body>
</html>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/datepicker.js"></script>
