<link rel="stylesheet" href="<?= $wwwUrl ?>/css/prestations.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<section class="header-landing header-table">
  <article class="titles-header-landing">
    <h1 class="title title-header-landing">Notre table d'hôtes</h1>
    <h2 class="title subtitle-header-landing">Ouverte tous les soirs sur réservations</h2>
  </article>
</section>
<section class="container-landing container-landing-first">
  <h2 class="title prestation-title">La table d'hôtes</h2>
  <article class="prestation-wrapper">
    <p>Nous vous proposons une table d'hôte essentiellement composée de produits provenant de producteurs situés à moins de 20 km.</p>
    <p>Cela nous permet de garantir la fraîcheur et la traçabilité de nos produits mais aussi de respecter
      l'environnement en diminuant les transports et enfin de soutenir financièrement les producteurs locaux que nous avons choisis, qui défendent une façon de produire raisonnée.</p>
    <p>Réserver au moins 24h avant! Précisez nous si vous avez des allergies ou des contraintes particulières</p>
    <p>Nous nous adaptons à vos envies. Si vous avez des allergies ou des intolérances, faites le nous savoir. Nous souhaitons bien manger mais surtout de manger sain.</p>
    <p>Avec des produits locaux, issus du marché du matin, nous assurons la fraîcheur et la traçabilité. Camille à la popotte, croyez nous, c'est un délice!!!</p>
  </article>
</section>
<section class="container-landing slider-prestation">
  <div class="slider">
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/table/1.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/table/2.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/table/3.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/table/4.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/table/5.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/table/6.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/table/7.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/table/8.jpg" alt="table d'hôtes tête à l'air">
      </figure>
  </div>
</section>
