<link rel="stylesheet" href="<?= $wwwUrl ?>/css/prestations.css">

<section>
  <h1 class="title-main">P'tit déj  et table d'hôtes</h1>
  <h2 class="title-main">Toujours local, toujours de saison, toujours fait avec amour !!</h2>
</section>
<section>
  <article class="prestations-food">
    <h3>P'tit déjeuner</h3>
    <h4><strong>Compris dans la réservation</strong></h4>
    <img src="<?= $wwwUrl ?>/images/prestations/ptit.webp" alt="petit déjeuner offert">
    <ul class="breakfast-presentation">
      <p>Nous proposons un petit déjeuner complet et à volonté:</p>
      <li>Café, chocolat, thé (plusieurs variétés), céréales</li>
      <li>Paint et viennoise</li>
      <li>beurre et confiture maison</li>
      <li>Jus de fruits</li>
      <li>Yaourts</li>
      <li>Fruits de saison</li>
    </ul>
  </article>
</section>
<section>
  <article class="prestations-food">
    <h3>Table d'hôtes</h3>
    <img src="<?= $wwwUrl ?>/images/prestations/table.webp" alt="Table d'hôtes">
    <div class="food-presentation">
      <p>Nous vous proposons une table d'hôte essentiellement composée de produits provenant de producteurs situés à moins de 20 km.</p>
      <p>Cela nous permet de garantir la fraîcheur et la traçabilité de nos produits mais aussi de respecter
        l'environnement en diminuant les transports et enfin de soutenir financièrement les producteurs locaux que nous avons choisis, qui défendent une façon de produire raisonnée.</p>
        <p>Réserver au moins 24h avant! Précisez nous si vous avez des allergies ou des contraintes particulières</p>
    </div>
    <p><strong>17 euros le menu simple (entrée plat dessert), sur devis pour une menu "sur mesure"</strong></p>
    <p>Nous nous adaptons à vos envies. Si vous avez des allergies ou des intolérances, faites le nous savoir. Nous souhaitons bien manger mais surtout de manger sain.</p>
    <p>Avec des produits locaux, issus du marché du matin, nous assurons la fraîcheur et la traçabilité. Camille à la popotte, croyez nous, c'est un délice!!!</p>
    </article>
  </section>
