<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/home.css">

<section>
  <h1 class="title title-main">Lucille et Camille vous souhaitent bienvenue</h1>
  <article>
    <p>A 15 km de Cognac, nous vous acceuillons au coeur de la Charente. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </article>
</section>
<section>
  <div class="presentation">
    <h2 class="title title-presentation">Profitez de tous les services que nous offrons :</h2>
    <article class="presentation-article">
      <img class="presentation-img"src="<?= $wwwUrl ?>/images/home/maison.jpg" alt="Maison charentaise">
      <!-- <h3 class="title title-presentation-article"><i class="fas fa-bed presentation-logo"></i></h3> -->
      <p>Ici, nous profitons du charme des maisons charentaises, de leur calme et leur fraicheur.</p>
      <p>Nous dormons dans une literie d'exception pour un sommeil réparateur.</p>
      <a class="cta" href="<?= $requestUrl ?>/rooms"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
    </article>
    <article class="presentation-article">
      <img class="presentation-img"src="<?= $wwwUrl ?>/images/home/repas.jpg" alt="table d'hôtes">
      <!-- <h3 class="title title-presentation-article"><i class="fas fa-utensils presentation-logo"></i></h3> -->
      <p>Nous privilégons la proximité, nous consommons "local".</p>
      <a class="cta" href="<?= $requestUrl ?>/prestations/table"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
    </article>
    <article class="presentation-article">
      <img class="presentation-img"src="<?= $wwwUrl ?>/images/home/ensemble.jpg" alt="La piscine">
      <!-- <h3 class="title title-presentation-article"><i class="fas fa-users presentation-logo"></i></h3> -->
      <p>Et surtout nous partageons des instants de convivialité dans notre salle ludique et près de la piscine.</p>
      <a class="cta" href="<?= $requestUrl ?>/prestations/commun"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
    </article>
  </div>
</section>
<section>
  <h2 class="title">Qui sommes-nous ?</h2>
  <p>Anciens cadres parisiens, nous avons décidé de tout quitter pour offrir à notre famille un meilleur cadre de vie. Aimant recevoir et amoureux de la campagne charentaise et de la qualité de ses produits régionaux, c'est naturellement que l'idée d'ouvrir des chambres d'hôtes nous est venue.</p>
</section>
