<!-- <link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/home.css"> -->

<section class="section-main-design prestations-overview">
  <h1 class="title title-main title-overview">Bienvenue aux chambres d'hôtes et gite tête à l'air</h1>
  <div class="prestations-overview-div prestations-overview-room">
    <div class="prestations-overview-inner-bloc">
      <a class="cta cta-overview" href="<?= $requestUrl ?>/rooms"><i class="fas fa-plus-circle"></i> Découvrez nos chambres d'hôtes</a>
    </div>
  </div>
  <div class="prestations-overview-div prestations-overview-games">
    <div class="prestations-overview-inner-bloc">
      <a class="cta cta-overview" href="<?= $requestUrl ?>/prestations/commun"><i class="fas fa-plus-circle"></i> Découvrez nos espaces communs</a>
    </div>
  </div>
  <div class="prestations-overview-div prestations-overview-pool">
    <div class="prestations-overview-inner-bloc">
      <a class="cta cta-overview" href="<?= $requestUrl ?>/prestations"><i class="fas fa-plus-circle"></i> Découvrez les prestations oiffertes dans nos chambres d'hôtes</a>
    </div>
  </div>
  <div class="prestations-overview-div prestations-overview-table">
    <div class="prestations-overview-inner-bloc">
      <a class="cta cta-overview" href="<?= $requestUrl ?>/prestations/table"><i class="fas fa-plus-circle"></i> Découvrez notre table d'hôtes</a>
    </div>
  </div>
  <article>
    <p>A 15 km de Cognac, nous vous acceuillons au coeur de la Charente. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </article>
</section>
<section class="section-main-design section-home">
  <article class="discover-around">
    <h2 class="title title-presentation">Découvrez Cognac et sa région</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <a class="cta" href="<?= $requestUrl ?>/around"><i class="fas fa-plus-circle"></i> Découvrez Cognac et ses alentours</a>
  </article>
</section>
<section class="section-main-design section-home">
  <h2 class="title">-10% sur les réservations en direct, appelez nous au 05.46.98.17.12 ou envoyez un mail</h2>
  <p>Les tarifs évoluent en fonction des saisons et du nombre de personnes. Contactez nous pour avoir un devis.</p>
  <p>Possibilité de payer en espèce, carte, chèque, chèque vacances</p>
</section>
