<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>Tête à l'air - Maison d'hôtes - Montils</title>
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/all.min.css">
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <!-- Feuilles de styles de l'application -->
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
  <link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/slick/slick.css"/>
  <!-- Add the new slick-theme.css if you want the default styling -->
  <link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/slick/slick-theme.css"/>
  <!-- Librairie jQuery -->
  <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

  <!-- JavaScript de l'application -->
  <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

  <!-- En-tête commune -->
  <header class="header">
    <div class="container menu">
      <a href="<?= $requestUrl ?>"><img src="<?= $wwwUrl ?>/images/logo/logo.webp" class="logo" alt="logo maison d'hôtes - Tête à l'air"></a>
      <nav class="nav-bar">
        <ul class="nav-list">
          <li class="nav-item"><a href="<?= $requestUrl ?>">Acceuil</a></li>
          <li class="nav-item" data-name="rooms">
            <a href="<?= $requestUrl ?>/rooms">Chambres et tarifs</a>
            <div class="navButton">
              <div class="sub-nav sub-nav-rooms hide">
                <ul class="sub-nav-list">
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/rooms/room?RoomId=1">Petite Champagne</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/rooms/room?RoomId=2">Grande Champagne</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/rooms/room?RoomId=3">La Borderie</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/rooms/room?RoomId=4">Les Fins Bois</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li class="nav-item" data-name="prestations">
            <a href="<?= $requestUrl ?>/prestations">Prestations</a>
            <div class="navButton">
              <div class="sub-nav sub-nav-prestations hide">
                <ul class="sub-nav-list">
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/prestations/table">Table d'hôtes</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/prestations/commun">Espaces Communs</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/prestations/event">Evénements</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li class="nav-item"><a href="<?= $requestUrl ?>/activités">Activités autour</a></li>
          <li class="nav-item"><a href="<?= $requestUrl ?>/livre">Livre d'or</a></li>
          <li class="nav-item"><a href="<?= $requestUrl ?>/contacts">Contacts</a></li>
          <li class="nav-item" data-name="profil">
            <i class="fas fa-user"></i>
            <div class="navButton">
              <div class="sub-nav sub-nav-profil hide">
                <ul class="sub-nav-list">
                  <?php if (array_key_exists("user", $_SESSION)) { ?>
                    <?php if ($_SESSION["user"]["role"] === "user") { ?>
                      <li class="sub-nav-item"><a href="<?= $requestUrl ?>/user/profil">Mon Profil</a></li>
                    <?php } else if ($_SESSION["user"]["role"] === "admin") { ?>
                      <li class="sub-nav-item"><a href="<?= $requestUrl ?>/user/admin">Admin</a></li>
                    <?php } ?>
                    <li class="sub-nav-item"><a href="<?= $requestUrl ?>/user/logout">Déconnexion</a></li>
                  <?php } else { ?>
                    <li class="sub-nav-item"><a href="<?= $requestUrl ?>/user/login">Connexion</a></li>
                    <li class="sub-nav-item"><a href="<?= $requestUrl ?>/user/register">S'enregistrer</a></li>
                  <?php } ?>
                </ul>
              </div>
            </div>
          </li>
        </ul>
      </nav>
    </div>
    </div>
  </header>
  <main class="container">
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template']; ?>
  </main>
  <!-- Pied de page commun -->
  <footer class="footer">
    <div class="container footer-informations">
      <a href="<?= $requestUrl ?>"><img src="<?= $wwwUrl ?>/images/logo/logo.webp" class="nav-logo" alt="logo maison d'hôtes - Tête à l'air"></a>
      <div class="contact">
        <h2 class="title contact-title">Nous contacter : </h3>
          <div class="contact-adress">
            <h3 class="title"><i class="fas fa-map-marker-alt"></i> Notre adresse :</h3>
            <p>Camille et Lucille Baret</p>
            <p>1 petit chemin des écoles</p>
            <p>17800 Montils</p>
          </div>
          <div class="contact-phone">
            <h3 class="title"><i class="fas fa-mobile-alt"></i> Notre téléphone :</h3>
            <p>05.46.98.17.12</p>
            <p>06.24.92.52.51</p>
          </div>
          <div class="contact-mail">
            <h3 class="title"><i class="fas fa-at"></i> Notre email :</h3>
            <p>camille.baret@hotmail.com</p>
          </div>
          <aside class="social-network">
            <ul class="social-network-list">
              <li class="social-network-list-items"><a href="https://www.facebook.com/T%C3%AAte-%C3%A0-lair-387782688636899/?view_public_for=387782688636899" target="_blank"><i class="fab fa-facebook-square social-network-logo"></i></a></li>
              <li class="social-network-list-items"><a href="https://www.instagram.com/tete_a_lair/"><i class="fab fa-instagram social-network-logo" target="_blank"></i></a></li>
              <li class="social-network-list-items"><a href="https://www.pinterest.fr/tetealair/"><i class="fab fa-pinterest-square social-network-logo" target="_blank"></i></a></li>
            </ul>
          </aside>
        </div>
    </div>
</footer>
<nav class="nav-footer">
  <ul class="nav-list-footer">
    <li><a href="<?= $requestUrl ?>">Acceuil</a></li>
    <li><a href="<?= $requestUrl ?>/rooms">Chambres et tarifs</a></li>
    <li><a href="<?= $requestUrl ?>/prestations">Prestations</a></li>
    <li><a href="<?= $requestUrl ?>/activités">Activités autour</a></li>
    <li><a href="<?= $requestUrl ?>/livre">Livre d'or</a></li>
    <li><a href="<?= $requestUrl ?>/contacts">Contacts</a></li>
  </ul>
</nav>

  <!-- Code principal JavaScript de l'application -->
  <script src="<?= $wwwUrl ?>/js/slider.js"></script>
  <script type="text/javascript" src="<?= $wwwUrl ?>/slick/slick.min.js"></script>
  <script src="<?= $wwwUrl ?>/js/main.js"></script>
</body>
</html>
