  <!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>Tête à l'air - Maison d'hôtes - Montils</title>
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/all.min.css">

  <!-- Intégration font-awesome -->
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <!-- Intégration font google -->
  <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&family=Cormorant+Garamond:wght@300&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Handlee&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">

  <!-- Feuilles de styles de l'application -->
  <!-- <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css"> -->
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style2.css">

  <!-- Feuille de style slickslider -->
  <link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/slick/slick.css"/>
  <!-- Add the new slick-theme.css if you want the default styling -->
  <link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/slick/slick-theme.css"/>

  <!-- Librairie jQuery -->
  <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

  <!-- Plugin Facebook comments -->
  <div id="fb-root"></div>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v7.0" nonce="yuZhzZWM"></script>

  <!-- JavaScript de l'application -->
  <script src="<?= $wwwUrl ?>/js/utilities.js"></script>

  <!-- Intégration CSS et JS Open street map -->
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin="" />
  <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
  
</head>
<body>

  <!-- En-tête commune -->
  <header class="header container">
    <div class="menu">
      <a href="<?= $requestUrl ?>"><img src="<?= $wwwUrl ?>/images/logo/logo.webp" class="logo" alt="logo maison d'hôtes - Tête à l'air"></a>
      <nav class="nav-bar">
        <ul class="nav-list">
          <li class="nav-item"><a href="<?= $requestUrl ?>">Acceuil</a></li>
          <li class="nav-item" data-name="rooms">
            <a href="<?= $requestUrl ?>/rooms">Chambres d'hôtes et gîte</a>
            <div class="navButton">
              <div class="sub-nav sub-nav-rooms hide">
                <ul class="sub-nav-list">
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/rooms/room?RoomId=1">Grande Champagne</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/rooms/room?RoomId=2">Petite Champagne</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/rooms/room?RoomId=3">La Borderie</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/rooms/room?RoomId=4">Les Fins Bois</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/rooms/room?RoomId=5">Gîte Calm</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li class="nav-item" data-name="prestations">
            <a href="<?= $requestUrl ?>/prestations">Nos Services et prestations</a>
            <div class="navButton">
              <div class="sub-nav sub-nav-prestations hide">
                <ul class="sub-nav-list">
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/prestations/table">Table d'hôtes</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/prestations/commun">Espaces intérieurs</a></li>
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/prestations/outside">Espaces extérieurs</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li class="nav-item" data-name="around">
            <a href="<?= $requestUrl ?>/around">Découvrir la Charentes</a>
            <div class="navButton">
              <div class="sub-nav sub-nav-around hide">
                <ul class="sub-nav-list">
                  <li class="sub-nav-item"><a href="<?= $requestUrl ?>/around/places">Nos adresses coup de coeur</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li class="nav-item"><a href="<?= $requestUrl ?>/comments">Livre d'or</a></li>
          <li class="nav-item"><a href="<?= $requestUrl ?>/contacts">Contacts</a></li>
          <!-- <li class="nav-item" data-name="profil">
            <i class="fas fa-user"></i>
            <div class="navButton">
              <div class="sub-nav sub-nav-profil hide">
                <ul class="sub-nav-list">
                  <?php if (array_key_exists("user", $_SESSION)) { ?>
                    <?php if ($_SESSION["user"]["role"] === "user") { ?>
                      <li class="sub-nav-item"><a href="<?= $requestUrl ?>/user/profil">Mon Profil</a></li>
                    <?php } else if ($_SESSION["user"]["role"] === "admin") { ?>
                      <li class="sub-nav-item"><a href="<?= $requestUrl ?>/user/admin">Admin</a></li>
                    <?php } ?>
                    <li class="sub-nav-item"><a href="<?= $requestUrl ?>/user/logout">Déconnexion</a></li>
                  <?php } else { ?>
                    <li class="sub-nav-item"><a href="<?= $requestUrl ?>/user/login">Connexion</a></li>
                    <li class="sub-nav-item"><a href="<?= $requestUrl ?>/user/register">S'enregistrer</a></li>
                  <?php } ?>
                </ul>
              </div>
            </div>
          </li> -->
        </ul>
      </nav>
    </div>
    </div>
  </header>
  <main class="container">
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template']; ?>
  </main>
  <!-- Pied de page commun -->
  <footer class="footer">
    <div class="container footer-informations">
      <a href="<?= $requestUrl ?>"><img src="<?= $wwwUrl ?>/images/logo/logo.webp" class="nav-logo" alt="logo maison d'hôtes - Tête à l'air"></a>
      <div class="contact">
        <h2 class="title contact-title">Nous contacter : </h3>
          <div class="contact-adress">
            <h3 class="title"><i class="fas fa-map-marker-alt"></i> Adresse :</h3>
            <p>Camille et Lucille Baret</p>
            <p>1 petit chemin des écoles</p>
            <p>17800 Montils</p>
          </div>
          <div class="contact-phone">
            <h3 class="title"><i class="fas fa-mobile-alt"></i> Téléphone :</h3>
            <ul class="phone-numbers">
              <li>
                <a href="tel:+33546981712">05.46.98.17.12</a>
              </li>
              <li>
                <a href="tel:+33624925251">06.24.92.52.51</a>
              </li>
            </ul>
          </div>
          <div class="contact-mail">
            <h3 class="title"><i class="fas fa-at"></i> E-mail :</h3>
            <a href="mailto:camille.baret@hotmail.com">camille.baret@hotmail.com</a>
          </div>
        </div>
        <aside class="social-network">
          <ul class="social-network-list">
            <li class="social-network-list-items"><a href="https://www.facebook.com/T%C3%AAte-%C3%A0-lair-387782688636899/?view_public_for=387782688636899" target="_blank"><i class="fab fa-facebook-square social-network-logo"></i></a></li>
            <li class="social-network-list-items"><a href="https://www.instagram.com/tete_a_lair/" target="_blank"><i class="fab fa-instagram social-network-logo"></i></a></li>
            <li class="social-network-list-items"><a href="https://www.pinterest.fr/tetealair/" target="_blank"><i class="fab fa-pinterest-square social-network-logo"></i></a></li>
          </ul>
        </aside>
    </div>
</footer>
<nav class="nav-footer">
  <ul class="nav-list-footer">
    <li><a href="<?= $requestUrl ?>">Acceuil</a></li>
    <li><a href="<?= $requestUrl ?>/rooms">Chambres d'hôtes et gîte</a></li>
    <li><a href="<?= $requestUrl ?>/prestations">Nos prestations et services</a></li>
    <li><a href="<?= $requestUrl ?>/around">Découvrir la Charentes</a></li>
    <li><a href="<?= $requestUrl ?>/comments">Livre d'or</a></li>
    <li><a href="<?= $requestUrl ?>/contacts">Contacts</a></li>
  </ul>
</nav>

  <!-- Code principal JavaScript de l'application -->
  <script src="<?= $wwwUrl ?>/js/slider.js"></script>
  <script type="text/javascript" src="<?= $wwwUrl ?>/slick/slick.min.js"></script>
  <script src="<?= $wwwUrl ?>/js/main.js"></script>
</body>
</html>
