<link rel="stylesheet" href="<?= $wwwUrl ?>/css/rooms.css">

<section class="header-landing header-rooms">
  <article class="titles-header-landing">
    <!-- <h1 class="title title-header-landing">Informations et réservations</h1>
    <h2 class="title subtitle-header-landing">Nous trouver, nous contacter</h2> -->
  </article>
</section>
<section class="container-landing container-landing-first">
  <p class="result">Nous avons bien reçu votre demande. Nous reviendrons vers vous rapidement.</p>
</section>
