<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/rooms.css">

<section class="header-landing" style="background-image: url('<?= $wwwUrl ?>/images/rooms/<?= $room['Photo1'] ?>')">
  <article class="titles-header-landing">
    <h1 class="title title-header-landing"><?= $room["RoomName"] ?></h1>
    <h2 class="title subtitle-header-landing">Pour <?= $room["NumberOfPersonn"] ?> personnes</h2>
  </article>
</section>
<section class="container-landing container-landing-first container-landing-room">
  <article class="wrapper-landing-header">
    <h3 class="title wrapper-landing-title"><?= $room["RoomName"] ?></h3>
    <span><hr></span>
    <article class="wrapper-landing-presentation">
      <p><?= $room["Description"] ?></p>
    </article>
  </article>
  <article class="wrapper-landing-images">
    <figure id="slider-room" class="slider-room">
      <img src="<?= $wwwUrl ?>/images/rooms/<?= $room['Photo1'] ?>" alt="<?= $room["RoomName"] ?>">
    </figure>
    <ul class="slider-room-list">
      <li class="slider-room-item" data-path="<?= $room['Photo1'] ?>" data-alt="<?= $room["RoomName"] ?>">
        <img src="<?= $wwwUrl ?>/images/rooms/<?= $room['Photo1'] ?>" alt="<?= $room["RoomName"] ?>">
      </li>
      <li class="slider-room-item" data-path="<?= $room['Photo2'] ?>" data-alt="<?= $room["RoomName"] ?>">
        <img src="<?= $wwwUrl ?>/images/rooms/<?= $room['Photo2'] ?>" alt="<?= $room["RoomName"] ?>">
      </li>
      <li class="slider-room-item" data-path="<?= $room['Photo3'] ?>" data-alt="<?= $room["RoomName"] ?>">
        <img src="<?= $wwwUrl ?>/images/rooms/<?= $room['Photo3'] ?>" alt="<?= $room["RoomName"] ?>">
      </li>
      <li class="slider-room-item" data-path="<?= $room['Photo4'] ?>" data-alt="<?= $room["RoomName"] ?>">
        <img src="<?= $wwwUrl ?>/images/rooms/<?= $room['Photo4'] ?>" alt="<?= $room["RoomName"] ?>">
      </li>
      <li class="slider-room-item" data-path="<?= $room['Photo5'] ?>" data-alt="<?= $room["RoomName"] ?>">
        <img src="<?= $wwwUrl ?>/images/rooms/<?= $room['Photo5'] ?>" alt="<?= $room["RoomName"] ?>">
      </li>
      <li class="slider-room-item" data-path="<?= $room['Photo6'] ?>" data-alt="<?= $room["RoomName"] ?>">
        <img src="<?= $wwwUrl ?>/images/rooms/<?= $room['Photo6'] ?>" alt="<?= $room["RoomName"] ?>">
      </li>
      <li class="slider-room-item" data-path="<?= $room['Photo7'] ?>" data-alt="<?= $room["RoomName"] ?>">
        <img src="<?= $wwwUrl ?>/images/rooms/<?= $room['Photo7'] ?>" alt="<?= $room["RoomName"] ?>">
      </li>
    </ul>
  </article>
</section>
<section class="container-landing room-details">
  <article class="wrapper-details room-equipements">
    <h3 class="title">Equipements</h3>
    <span><hr></span>
    <ul class="room-equipements-list">
      <li class="room-equipements-item"><?= $room["Bed"] ?></li>
      <?php if ($room["RelaxSpace"] == 1) { ?>
        <li class="room-equipements-item">Salon</li>
      <?php } ?>
      <?php if ($room["WithCouch"] == 1) { ?>
        <li class="room-equipements-item">Canapé</li>
      <?php } ?>
      <?php if ($room["WithBabyBed"] == 1) { ?>
        <li class="room-equipements-item">Lit pour bébé</li>
      <?php } ?>
      <?php if ($room["Office"] == 1) { ?>
        <li class="room-equipements-item">Bureau</li>
      <?php } ?>
      <li class="room-equipements-item">Salle de bain privative</li>
      <?php if ($room["SeperateWC"] == 1) { ?>
        <li class="room-equipements-item">WC Séparé</li>
      <?php } ?>
      <?php if ($room["PlusBed"]) { ?>
        <li class="room-equipements-item">Possibilité de rajouter un lit</li>
      <?php } ?>
      <?php if ($room["RoomType"] === "lodging") { ?>
        <li class="room-equipements-item">Cuisine équipée</li>
        <li class="room-equipements-item">Ustensibles de cuisine</li>
        <li class="room-equipements-item">Couverts</li>
        <li class="room-equipements-item">Télévision</li>
        <li class="room-equipements-item">terrasse</li>
      <?php } ?>
    </ul>
  </article>
  <article class="wrapper-details room-informations">
    <h3 class="title">Informations</h3>
    <span><hr></span>
    <article>
      <p>Arrivé : 15h30 - 22h</p>
      <p>Départ : avant 12h</p>
    </article>
    <article>
      <p>Table d'hôtes ouverte tous  les soirs sur réservation.</p>
    </article>
    <article>
      <p>Petit déjeuner buffet offert tous les matins</p>
    </article>
  </article>
  <article class="wrapper-details room-price">
    <h3 class="title">Tarifs</h3>
    <span><hr></span>
    <p>A partir de : <?= $room["LowSeasonPriceDay"] ?> €</p>
    <a id="reservationCTA" class="cta cta-booking-details" href="#reservationBloc">Réservez Maintenant</a>
  </article>
</section>


<section id="reservationBloc" class="container-landing container-landing-second wrapper-reservation">
  <h2 class="title">Réservez une chambre</h2>
  <form class="form-reservation" action="<?= $requestUrl ?>/booking" method="post">
    <label for="arrivalDate">Date d'arrivée</label>
    <input type="date" id="dateArrival" name="dateArrival">
    <label for="departureDate">Date de départ</label>
    <input type="date" id="dateDeparture" name="dateDeparture">
    <input type="hidden" name="roomId" value="<?= $_GET["RoomId"] ?>">
    <input type="submit" id="bookingCta" class="hide" value="Réservez" />
  </form>
</section>

<!-- <script type="text/javascript" src="<?= $wwwUrl ?>/js/datepicker.js"></script> -->
<script type="text/javascript" src="<?= $wwwUrl ?>/js/date.js"></script>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/slider-room.js"></script>
