<link rel="stylesheet" href="<?= $wwwUrl ?>/css/around.css">

<section class="section-main-design">
  <h1 class="title-main">Découvrez la Charentes selon vos envies</h1>
  <article class="program-introduction">
    <p>Montils est un petit bourg situé dans le triangle Saintes / Cognac / Pons. C’est un point de départ stratégique pour visiter ces villes historiques et déguster cognac et pineau qui font leur réputation. Découvrez la Charentes et sa région grâce aux programmes que nous vous avons concocté.</p>
  </article>
  <div class="program-list">
    <article class="program-overview">
      <img src="<?= $wwwUrl ?>/images/around/program/1.png" alt="Le sport en charentes" title="le sport en charentes">
      <h2 class="title">Les sportifs</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <a class="cta" href="<?= $requestUrl ?>/around"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
    </article>
    <article class="program-overview">
      <img src="<?= $wwwUrl ?>/images/around/program/2.jpg" alt="Les séniors en charentes" title="le séniors en charentes">
      <h2 class="title">Les séniors</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <a class="cta" href="<?= $requestUrl ?>/around"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
    </article>
    <article class="program-overview">
      <img src="<?= $wwwUrl ?>/images/around/program/3.jpg" alt="Les séniors en charentes" title="le séniors en charentes">
      <h2 class="title">Les soiffars</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <a class="cta" href="<?= $requestUrl ?>/around"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
    </article>
  </div>
</section>
