<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/rooms.css">

<section class="room-presentation">
  <h2 class="title title-room-presentation"><?= $room["RoomName"] ?> (<?= $room["NumberOfPersonn"] ?>)</h3>
  <article class="room-introduction">
    <p><?= $room["Description"] ?></p>
    <?php if ($room["PlusBed"]) { ?>
      <p>Possibilité de mettre un lit supplémentaire (supplément 15 euros)</p>
    <?php } ?>
    <img class="room-picture" src="<?= $wwwUrl ?>/images/rooms<?= $room["PhotoMiniature"] ?>" alt="Photos de la chambre d'hôtes <?= $room["RoomName"] ?>">
    <article class="room-services">
      <ul class="room-presentation-list">
        <li>Entrée privative</li>
        <li>Chambre avec un lit <?= $room["Bed"] ?></li>
        <?php if ($room["SeperateWC"]) { ?>
          <li>Salle de douche et WC privatifs mais WC séparés</li>
        <?php } else { ?>
          <li>Salle de douche et WC privatifs</li>
        <?php } ?>
        <?php if ($room["RelaxSpace"]) { ?>
          <li>Coin Détente</li>
        <?php } ?>
        <?php if ($room["WithBabyBed"]) { ?>
          <li>Lit gigogne</li>
        <?php } ?>
        <?php if ($room["WithCouch"]) { ?>
          <li>Canapé</li>
        <?php } ?>
        <?php if ($room["Office"]) { ?>
          <li>Coin Bureau</li>
        <?php } ?>
      </ul>
    </article>
  </article>
  <aside class="room-prices">
    <?php if ($error === null) { ?>
      <h3 class="title">Réservation du <?= $dateArrival ?> au <?= $dateDeparture ?></h3>
      <h4 class="title"><?= $reservationDetails[0]["days"] +  $reservationDetails[0]["weeks"] * 7 ?>  jours</h4>
      <p>Total TTC : <strong><?= $reservationDetails[4] ?> €</p>
      <a class="cta" href="<?= $requestUrl ?>/reservation/charge">Payez !</a>
    <?php } else { ?>
      <p><strong><?= $error ?></strong></p>
    <?php } ?>
  </aside>
</section>
<?php if ($error === null) { ?>
  <section>
    <h2 class="title title-main">Détails de votre réservation</h2>
    <table>
      <legend>Détails</legend>
      <thead>
        <tr>
          <th>Nom de la chambre</th>
          <th>Nombre de nuits</th>
          <th>Prix par nuit</th>
          <th>Montant HT</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td></td>
          <td colspan="2">Montant TTC</td>
          <td></td>
          <td><?= $reservationDetails[4] ?> €</td>
        </tr>
      </tfoot>
      <tbody>
        <tr>
          <td><?= $room["RoomName"] ?></td>
          <td><?= $reservationDetails[0]["days"] +  $reservationDetails[0]["weeks"] * 7 ?></td>
          <td><?= round($reservationDetails[4] / ($reservationDetails[0]["days"] +  $reservationDetails[0]["weeks"] * 7 ), 2)?> €</td>
          <td><?= $reservationDetails[1] ?> €</td>
        </tr>
        <tr>
          <td></td>
          <td colspan="2">Montant de la TVA (<?= $reservationDetails[2] ?>%)</td>
          <td></td>
          <td><?= $reservationDetails[3] ?> €</td>
        </tr>
      </tbody>
    </table>
    <a class="cta" href="<?= $requestUrl ?>/reservation/charge">Payez !</a>
  </section>
<?php } ?>
<section>
  <h2 class="title title-main">Les autres chambres diponibles à ces dates</h2>
</section>
<?php for ($i = 0; $i < count($roomAvailablePrice); $i++) { ?>
  <section class="room-presentation">
    <h2 class="title title-room-presentation"><?= $roomAvailableDetails[$i]["RoomName"] ?> (<?= $roomAvailableDetails[$i]["NumberOfPersonn"] ?>)</h3>
    <article class="room-introduction">
      <p><?= $roomAvailableDetails[$i]["Description"] ?></p>
      <?php if ($roomAvailableDetails[$i]["PlusBed"]) { ?>
        <p>Possibilité de mettre un lit supplémentaire (supplément 15 euros)</p>
      <?php } ?>
      <img class="room-picture" src="<?= $wwwUrl ?>/images/rooms<?= $roomAvailableDetails[$i]["PhotoMiniature"] ?>" alt="Photos de la chambre d'hôtes <?= $roomAvailableDetails[$i]["RoomName"] ?>">
      <article class="room-services">
        <ul class="room-presentation-list">
          <li>Entrée privative</li>
          <li>Chambre avec un lit <?= $roomAvailableDetails[$i]["Bed"] ?></li>
          <?php if ($roomAvailableDetails[$i]["SeperateWC"]) { ?>
            <li>Salle de douche et WC privatifs mais WC séparés</li>
          <?php } else { ?>
            <li>Salle de douche et WC privatifs</li>
          <?php } ?>
          <?php if ($roomAvailableDetails[$i]["RelaxSpace"]) { ?>
            <li>Coin Détente</li>
          <?php } ?>
          <?php if ($roomAvailableDetails[$i]["WithBabyBed"]) { ?>
            <li>Lit gigogne</li>
          <?php } ?>
          <?php if ($roomAvailableDetails[$i]["WithCouch"]) { ?>
            <li>Canapé</li>
          <?php } ?>
          <?php if ($roomAvailableDetails[$i]["Office"]) { ?>
            <li>Coin Bureau</li>
          <?php } ?>
        </ul>
      </article>
    </article>
    <aside class="room-prices">
      <h3 class="title">Réservation du <?= $dateArrival ?> au <?= $dateDeparture ?></h3>
      <h4 class="title"><?= $roomAvailablePrice[$i][0]["days"] +  $roomAvailablePrice[$i][0]["weeks"] * 7 ?>  jours</h4>
      <p>Total TTC : <strong><?= $roomAvailablePrice[$i][4] ?> €</p>
    </aside>
  </section>
<?php } ?>
