<link rel="stylesheet" href="<?= $wwwUrl ?>/css/comments.css">

<section class="header-landing" style="background-image: url('<?= $wwwUrl ?>/images/background/maison.jpg')">
  <article class="titles-header-landing">
    <h1 class="title title-header-landing">Ce que vous pensez de nous</h1>
  </article>
</section>
<section class="container-landing container-landing-first">
  <h2 class="title title-container-landing">Vos témoignages</h2>
  <article class="">
    <div class="fb-comments" data-href="https://www.facebook.com/T%C3%AAte-%C3%A0-lair-387782688636899/?ref=page_internal" data-numposts="10" data-width="100%" data-colorscheme="dark"></div>
  </article>
</section>
