<link rel="stylesheet" href="<?= $wwwUrl ?>/css/comments.css">

<section class="section-main-design">
  <h1 class="title-main">Vos témoignages</h1>
  <aside class="social-comments">
    <div class="fb-comments" data-href="https://www.facebook.com/T%C3%AAte-%C3%A0-lair-387782688636899/?ref=page_internal" data-numposts="10" data-width="100%" data-colorscheme="dark"></div>
  </aside>
  <!-- Rajouter plugin google (https://support.google.com/business/answer/7035772?hl=fr) -->
</section>
