<link rel="stylesheet" href="<?= $wwwUrl ?>/css/around.css">

<section class="header-landing header-places">
  <article class="titles-header-landing">
    <h1 class="title title-header-landing">Nos adresses coup de coeur</h1>
    <h2 class="title subtitle-header-landing">Découvrir La Charentes</h2>
  </article>
</section>
<section class="container-landing container-landing-first">
  <h2 class="title">Que faire en Charentes ?</h2>
  <div id="map">

  </div>
</section>
<section class="container-landing container-landing-second">
  <h2 class="title">Nous vous conseillons de découvrir ces lieux</h2>
  <div id="sites-container">
  </div>
</section>

<script type="text/javascript" src="<?= $wwwUrl ?>/js/openstreetmap.js"></script>
