<link rel="stylesheet" href="<?= $wwwUrl ?>/css/prestations.css">

<section class="header-landing header-prestations">
  <article class="titles-header-landing">
    <h1 class="title title-header-landing">Nos différents espaces</h1>
    <h2 class="title subtitle-header-landing">Pour se relaxer, jouer, partager</h2>
  </article>
</section>
<section class="container-landing container-landing-first">
  <div class="prestation-container">
    <img class="prestation-picture" src="<?= $wwwUrl ?>/images/prestations/3.jpg" alt="Table d'hotes tête à l'air">
    <article class="prestation-wrapper">
      <h2 class="title prestation-title">La table d'hôtes</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <a class="cta-prestation" href="<?= $requestUrl ?>/prestations/table">Découvrez notre table d'hôtes</a>
    </article>
  </div>
</section>
<section class="container-landing container-landing-second">
  <div class="prestation-container">
    <article class="prestation-wrapper">
      <h2 class="title prestation-title">Nos espaces extérieurs</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <a class="cta-prestation" href="<?= $requestUrl ?>/prestations/outside">Découvrez nos espaces extérieurs</a>
    </article>
    <img class="prestation-picture" src="<?= $wwwUrl ?>/images/prestations/1.jpg" alt="La piscine tête à l'air">
  </div>
</section>
<section class="container-landing container-landing-second">
  <div class="prestation-container">
    <img class="prestation-picture" src="<?= $wwwUrl ?>/images/prestations/ludo.webp" alt="La ludothèque tête à l'air">
    <article class="prestation-wrapper">
      <h2 class="title prestation-title">Nos espaces intérieurs</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <a class="cta-prestation" href="<?= $requestUrl ?>/prestations/commun">Découvrez nos espaces intérieurs</a>
    </article>
  </div>
</section>
