<link rel="stylesheet" href="<?= $wwwUrl ?>/css/prestations.css">

<section class="prestations">
  <h1 class="title title-main">Nos Prestations</h1>
  <div class="slider">
    <div class="slider-pictures"><img class="slider-picture" src="<?= $wwwUrl ?>/images/prestations/3.jpg" alt="Tâbles d'hôtes"></div>
    <div class="slider-pictures"><img class="slider-picture" src="<?= $wwwUrl ?>/images/prestations/swimming.webp" alt="La piscine de la maison d'hôtes"></div>
    <div class="slider-pictures"><img class="slider-picture" src="<?= $wwwUrl ?>/images/prestations/ludo.webp" alt="La ludothèque de la maison d'hôtes"></div>
    <div class="slider-pictures"><img class="slider-picture" src="<?= $wwwUrl ?>/images/prestations/garden.webp" alt="Le jardin de la maison d'hôtes"></div>
    <div class="slider-pictures"><img class="slider-picture" src="<?= $wwwUrl ?>/images/prestations/gaming.webp" alt="Super Nes et jeux de société disponible"></div>
  </div>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <div class="prestations-list">
    <article class="prestations-presentations">
      <img src="<?= $wwwUrl ?>/images/prestations/3.jpg" alt="Tâbles d'hôtes">
      <h2 class="title">Table d'hôtes</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <a class="cta" href="<?= $requestUrl ?>/prestations/table"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
    </article>
    <article class="prestations-presentations">
      <img src="<?= $wwwUrl ?>/images/prestations/1.jpg" alt="Piscines de la maison d'hôtes">
      <h2 class="title">Espaces communs</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <a class="cta" href="<?= $requestUrl ?>/prestations/commun"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
    </article>
    <article class="prestations-presentations">
      <img src="<?= $wwwUrl ?>/images/prestations/2.jpg" alt="Organisation d'événements">
      <h2 class="title">Vos évenements</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <a class="cta" href="<?= $requestUrl ?>/prestations/event"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
    </article>
  </div>
</section>
