<link rel="stylesheet" href="<?= $wwwUrl ?>/css/prestations.css">

<section class="prestations">
  <h1 class="title title-main">Nos Prestations</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <article class="prestations-presentations">
    <img src="<?= $wwwUrl ?>/images/prestations/1.jpg" alt="Piscine de la maison d'hôtes">
    <h2 class="title">Table d'hôtes</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <a class="cta" href="<?= $requestUrl ?>/prestations/table"><i class="fas fa-plus-circle"></i> Plus d'informations</a>
  </article>
</section>
