<link rel="stylesheet" href="<?= $wwwUrl ?>/css/prestations.css">


<section class="section-main-design">
  <h1 class="title-main">Vos événements</h1>
  <h2 class="title-main">Sur devis, selon les besoins</h2>
  <p>Vous avez la possibilité de privatiser l'ensemble des chambres et la salle commune pour organiser vos événements (cousinade, baptême, mariage...). Nous serons heureux de vous aider.</p>
  <p>Exposez nous votre projet, nous ferons notre possible pour vous accompagner.</p>
  <p>Au besoin, la salle des fêtes de Montils est accessible à pied. Réservez la salle des fêtes <a href="http://www.montils.fr/fr/salle-municipale/1861/salle-fetes-montils">ici</a></p>
</section>
