<link rel="stylesheet" href="<?= $wwwUrl ?>/css/prestations.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<section class="header-landing header-outside">
  <article class="titles-header-landing">
    <h1 class="title title-header-landing">Nos espaces extérieurs</h1>
    <h2 class="title subtitle-header-landing">Nos petits coins détentes</h2>
  </article>
</section>
<section class="container-landing container-landing-first">
  <h2 class="title title-wrapper">Nos espace communs extérieurs</h2>
  <article class="prestation-wrapper">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </article>
</section>
<section class="container-landing slider-prestation">
  <div class="slider">
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/outside/1.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/outside/2.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/outside/3.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/outside/4.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/outside/5.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/outside/6.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/outside/7.jpg" alt="table d'hôtes tête à l'air">
      </figure>
      <figure>
        <img class="prestation-item" src="<?= $wwwUrl ?>/images/prestations/outside/8.jpg" alt="table d'hôtes tête à l'air">
      </figure>
  </div>
</section>
