<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/rooms.css">

<section class="header-landing" style="background-image: url('<?= $wwwUrl ?>/images/rooms/<?= $room['PhotoMiniature'] ?>')">
  <article class="titles-header-landing">
    <h1 class="title title-header-landing"><?= $room["RoomName"] ?></h1>
    <h2 class="title subtitle-header-landing">Pour <?= $room["NumberOfPersonn"] ?> personnes</h2>
  </article>
</section>
<section class="container-landing container-landing-first container-booking">
  <?php if ($available) { ?>
    <article class="wrapper-booking-image">
      <figure class="booking-image">
        <img src="<?= $wwwUrl ?>/images/rooms/<?= $pictures['Photo2'] ?>" alt="<?= $room["RoomName"] ?>">
      </figure>
    </article>
    <article class="wrapper-booking-details">
      <h3 class="title wrapper-landing-title"><?= $room["RoomName"] ?></h3>
      <span><hr></span>
      <article class="wrapper-landing-presentation">
        <p>Réservation du <?= $dateArrivalFr ?> au  <?= $dateDepartureFr ?></p>
        <p>Nombre de nuits : <?= $bookingDetails["duration"] ?></p>
        <p>Prix total : <?= $bookingDetails["totalHT"] ?> €</p>
        <h3 class="title">Services inclus dans la réservation :</h3>
        <ul>
          <?php if ($bookingDetails["roomType"] === "room") { ?>
            <li>Draps</li>
            <li>Serviettes</li>
            <li>Petit déjeuner </li>
          <?php } ?>
          <li>WIFI</li>
          <li>Espace extérieur</li>
        </ul>
        <span class="table">Pour les repas du soir vous pouvez réserver à notre table d'hôtes.</span>
        <a id="booking-cta" class="cta cta-booking" href="#booking-wrapper">Réservez</a>
    </article>
  <?php } else { ?>
    <h2 class="title title-container-landing">Désolé, cette chambre n'est pas disponible</h2>
  <?php } ?>
</article>
</section>
<?php if ($available) { ?>
<section id="booking-wrapper" class="container-landing container-landing-second booking-form hide">
  <form id="booking-form" action="<?= $requestUrl ?>/booking/process" method="post">
    <legend class="title title-booking-details">Vos informations</legend>
    <input type="hidden" name="room-id" value="<?= $bookingDetails["roomId"] ?>">
    <input type="hidden" name="room-name" value="<?= $room["RoomName"] ?>">
    <input type="hidden" name="arrival" value="<?= $dateArrival ?>">
    <input type="hidden" name="departure" value="<?= $dateDeparture ?>">
    <input type="hidden" name="duration" value="<?= $bookingDetails["duration"] ?>">
    <input type="hidden" name="price" value="<?= $bookingDetails["totalHT"] ?>">
    <name>
      <input class="contact-us-informations" type="text" name="name" placeholder="Nom*">
      <span id="error-name" class="error-message hide"></span>
    </name>
    <surname>
      <input class="contact-us-informations" type="text" name="surname" placeholder="Prénom*">
      <span id="error-surname" class="error-message hide"></span>
    </surname>
    <email>
      <input class="contact-us-informations" type="text" name="email" placeholder="Email*">
      <span id="error-email" class="error-message hide"></span>
    </email>
    <phone>
      <input class="contact-us-informations" type="text" name="phoneNumber" placeholder="Téléphone*">
      <span id="error-phone" class="error-message hide"></span>
    </phone>
    <input class="booking-send" type="submit" value="Envoyez !">
    <p>* champs obligatoire</p>
  </form>
</section>
<?php } ?>
<section class="container-landing container-landing-second">
  <h2 class="title title-container-landing">Nos autres chambres disponibles aux mêmes dates</h2>
  <h3 class="title subtitle-container-landing">Nos chambres d'hôtes au coeur d'une maison charentaise</h3>
</section>
<section class="container-landing rooms-list">
<?php foreach ($roomsAvailableBookingDetails as $roomAvailableBookingDetails) { ?>
  <?php if ($roomAvailableBookingDetails["roomType"] === "room") { ?>
    <article class="room-wrap">
      <img class="room-picture" src="<?= $wwwUrl ?>/images/rooms/<?= $roomAvailableBookingDetails["photoMiniature"] ?>" alt="Photos de la chambre d'hôtes <?= $roomAvailableBookingDetails["roomName"] ?>">
      <h3 class="title title-wrapper"><?= $roomAvailableBookingDetails["roomName"] ?></h3>
      <h4 class="title subtitle-room">Pour <?= $roomAvailableBookingDetails["numberOfPersonn"] ?> personnes</h4>
      <a class="cta cta-room" href="<?= $requestUrl ?>/rooms/room?RoomId=<?= $roomAvailableBookingDetails["roomId"] ?>">Voir la chambre</a>
    </article>
  <?php } ?>
<?php } ?>
</section>
<?php foreach ($roomsAvailableBookingDetails as $roomAvailableBookingDetails) { ?>
  <?php if ($roomAvailableBookingDetails["roomType"] === "lodging") { ?>
    <section class="container-landing container-landing-second">
      <h2 class="title title-container-landing">Notre gîte est disponible aux mêmes dates</h2>
      <h3 class="title subtitle-container-landing">Gite typique en pierre charentaise</h3>
    </section>
    <section class="container-landing rooms-list">
    <article class="room-wrap">
      <img class="room-picture" src="<?= $wwwUrl ?>/images/rooms/<?= $roomAvailableBookingDetails["photoMiniature"] ?>" alt="Photos de la chambre d'hôtes <?= $roomAvailableBookingDetails["roomName"] ?>">
      <h3 class="title title-wrapper"><?= $roomAvailableBookingDetails["roomName"] ?></h3>
      <h4 class="title subtitle-room">Pour <?= $roomAvailableBookingDetails["numberOfPersonn"] ?> personnes</h4>
      <a class="cta cta-room" href="<?= $requestUrl ?>/rooms/room?RoomId=<?= $roomAvailableBookingDetails["roomId"] ?>">Voir la chambre</a>
    </article>
  </section>
  <?php } ?>
<?php } ?>

<script type="text/javascript" src="<?= $wwwUrl ?>/js/booking.js"></script>
