<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/rooms.css">
<section>
  <h1 class="title title-rooms">Nos Chambres d'hôtes</h1>
  <div class="slider">
    <div><img class="slider-picture" src="<?= $wwwUrl ?>/images/rooms/petite-champagne/1.jpg" alt="Photos de la chambre d'hôtes Petite Champagne"></div>
    <div><img class="slider-picture" src="<?= $wwwUrl ?>/images/rooms/grande-champagne/1.jpg" alt="Photos de la chambre d'hôtes Grande Champagne"></div>
    <div><img class="slider-picture" src="<?= $wwwUrl ?>/images/rooms/borderie/1.jpg" alt="Photos de la chambre d'hôtes borderie"></div>
    <div><img class="slider-picture" src="<?= $wwwUrl ?>/images/rooms/fin-bois/1.jpg" alt="Photos de la chambre d'hôtes fins bois"></div>
  </div>
</section>
<section class="rooms-main">
  <h2 class="title title-sub-rooms">Découvrez nos chambres typiquement charentaise</h2>
  <p>Elles disposent chacune d'une entrée privative, ainsi que leur propre salle de bain et WC.</p>
  <div class="rooms-introduction">
    <article class="rooms-presentation">
      <h3 class="title">Les services de nos chambres d'hôtes</h3>
      <ul class="rooms-presentation-list">
        <li>Notre literie 100% française est de très bonne qualité</li>
        <li>Les draps et les serviettes sont fournis</li>
        <li>Wi-Fi gratuit</li>
        <li>Plusieurs parkings à proximité, possibilité de rentrer quelques voitures dans la cours</li>
        <li>Petit déjeuner compris</li>
      </ul>
    </article>
    <aside class="reservation-offer">
      <h3 class="title title-reservation-offer"><strong>-10 %</strong> sur le prix si vous réservez en direct !!!</h3>
    </aside>
  </div>
</section>
<section class="room-presentation">
  <h3 class="title title-room-presentation">La petite champagne (3 personnes)</h3>
  <img class="room-picture" src="<?= $wwwUrl ?>/images/rooms/petite-champagne/1.jpg" alt="Photos de la chambre d'hôtes Petite Champagne">
  <article class="room-services">
    <p>Chambre d'hôte familiale, idéale pour un couple avec 1 ou 2 enfants.</p>
    <p>Possibilité de mettre un lit supplémentaire (supplément 15 euros)</p>
    <ul class="room-presentation-list">
      <li>Entrée privative</li>
      <li>Chambre lit queen size</li>
      <li>Salle de douche et WC privatifs</li>
      <li>Coin détente avec lit gigogne</li>
      <li>Espace bureau</li>
    </ul>
  </article>
  <aside class="room-prices">
    <h3>A partir de 70€</h3>
    <p>Supplément 10 € pour 1 personne supplémentaire</p>
    <p>Petit déjeuner INCLUS</p>
    <a class="cta" href="<?= $requestUrl ?>/chambres/petite"><i class="fas fa-plus-circle"></i> Voir plus</a>
  </aside>
</section>
<section class="room-presentation">
  <h3 class="title title-room-presentation">La grande champagne (4 personnes)</h3>
  <img class="room-picture" src="<?= $wwwUrl ?>/images/rooms/grande-champagne/1.jpg" alt="Photos de la chambre d'hôtes Grande Champagne">
  <article class="room-services">
    <p>Chambre d'hôte familiale, idéale pour 2 couples ou 1 couple avec enfants.</p>
    <p>Possibilité de mettre un lit supplémentaire (supplément 15 euros)</p>
    <ul class="room-presentation-list">
      <li>Entrée privative</li>
      <li>Chambres avec lit queen size</li>
      <li>Salle de douche et WC privatifs</li>
      <li>Coin détente</li>
      <li>Espace bureau</li>
    </ul>
  </article>
  <aside class="room-prices">
    <h3>A partir de 85€</h3>
    <p>Supplément 10 € pour 1 personne supplémentaire</p>
    <p>Petit déjeuner INCLUS</p>
    <a class="cta" href="<?= $requestUrl ?>/chambres/grande"><i class="fas fa-plus-circle"></i> Voir plus</a>
  </aside>
</section>
<section class="room-presentation">
  <h3 class="title title-room-presentation">La borderie (2 personnes jusqu'à 4 personnes)</h3>
  <img class="room-picture" src="<?= $wwwUrl ?>/images/rooms/borderie/1.jpg" alt="Photos de la chambre d'hôtes borderie">
  <article class="room-services">
    <p>Chambre d'hôte, idéal pour un couple.... salle de bain ouverte.</p>
    <ul class="room-presentation-list">
      <li>Entrée privative</li>
      <li>Chambre avec lit king size (180 x 200 cm)</li>
      <li>WC privatifs et séparés</li>
      <li>Espace détente avec canapé</li>
    </ul>
  </article>
  <aside class="room-prices">
    <h3>A partir de 60€</h3>
    <p>Supplément 10 € pour 1 personne supplémentaire</p>
    <p>Petit déjeuner INCLUS</p>
    <a class="cta" href="<?= $requestUrl ?>/chambres/borderie"><i class="fas fa-plus-circle"></i> Voir plus</a>
  </aside>
</section>
<section class="room-presentation">
  <h3 class="title title-room-presentation">Les fins bois (2 personnes)</h3>
  <img class="room-picture" src="<?= $wwwUrl ?>/images/rooms/fin-bois/1.jpg" alt="Photos de la chambre d'hôtes fins bois">
  <article class="room-services">
    <p>Chambre d'hôte, idéal pour un couple.... </p>
    <ul class="room-presentation-list">
      <li>Entrée privative</li>
      <li>Chambre avec lit queen size</li>
      <li>Salle de douche et WC privatifs</li>
      <li>Espace bureau</li>
    </ul>
  </article>
  <aside class="">
    <h3>A partir de 55€</h3>
    <p>Petit déjeuner INCLUS</p>
    <a class="cta" href="<?= $requestUrl ?>/chambres/finsbois"><i class="fas fa-plus-circle"></i> Voir plus</a>
  </aside>
</section>
