<link rel="stylesheet" href="<?= $wwwUrl ?>/css/prestations.css">

<section>
  <h1 class="title-main">Espaces communs</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</section>
<section>
  <article class="commun-presentation">
    <h2 class="title">La piscine</h2>
    <img class="commun-img" src="<?= $wwwUrl ?>/images/prestations/swimming.webp" alt="La piscine de la maison d'hôtes">
    <p>Avec salon de jardin pour les journées farnientes</p>
  </article>
</section>
<section>
  <article class="commun-presentation">
    <h2 class="title">Ludothèque / Bibliothèque</h2>
    <img class="commun-img" src="<?= $wwwUrl ?>/images/prestations/ludo.webp" alt="La ludothèque de la maison d'hôtes">
    <p>Des jeux et des livres pour tous les âges</p>
  </article>
</section>
<section>
  <article class="commun-presentation">
    <h2 class="title">Jardin</h2>
    <img class="commun-img" src="<?= $wwwUrl ?>/images/prestations/garden.webp" alt="Le jardin de la maison d'hôtes">
    <p>Avec balançoire et verger</p>
  </article>
</section>
<section>
  <article class="commun-presentation">
    <h2 class="title">Espace rétro-gaming</h2>
    <img class="commun-img" src="<?= $wwwUrl ?>/images/prestations/gaming.webp" alt="Super Nes et jeux de société disponible">
    <p>La super ness pour un retour en enfance</p>
  </article>
</section>
